site_name: GW2 Team Builder
site_url: https://your-username.github.io/gw2-team-builder
repo_url: https://github.com/your-username/gw2-team-builder
repo_name: your-username/gw2-team-builder

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - meta
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_category_heading: true
            show_submodules: true

nav:
  - Home: index.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Getting Started: user-guide/getting-started.md
      - Advanced Usage: user-guide/advanced-usage.md
  - API Reference:
      - Modules: api/modules.md
  - Development:
      - Contributing: development/contributing.md
      - Code of Conduct: development/code-of-conduct.md
      - Changelog: development/changelog.md

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

watch:
  - .

docs_dir: docs
site_dir: site

strict: true

copyright: Copyright &copy; 2025 GW2 Team Builder Team
