server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs de l'application
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: gw2-teambuilder
          __path__: /var/log/app/*.log

  # Logs des conteneurs Docker
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_file']
        target_label: 'log_file'
      - source_labels: ['__meta_docker_container_name']
        regex: '/([^/]+)'
        target_label: 'container_name'

  # Logs système
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/syslog

# Pipeline de traitement des logs
pipeline_stages:
  - docker: {}
  - regex:
      expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<log>.*)'
  - labels:
      stream:
  - timestamp:
      source: timestamp
      format: RFC3339
