"""Initial migration for Build model

Revision ID: 5877d8f56456
Revises: 
Create Date: 2025-07-14 11:58:37.733662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5877d8f56456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajout des colonnes created/updated avec nullable=True pour toutes les tables
    tables = [
        'armors', 'infusions', 'item_stat_mapping', 'item_stats', 'items',
        'profession_armor_types', 'profession_armors', 'profession_trinket_types',
        'profession_trinkets', 'profession_weapon_skills', 'profession_weapon_types',
        'profession_weapons', 'traits', 'trinkets', 'upgrade_components', 'weapons'
    ]
    
    for table in tables:
        op.add_column(table, sa.Column('created', sa.DateTime(), nullable=True))
        op.add_column(table, sa.Column('updated', sa.DateTime(), nullable=True))

    # Création de l'index pour la table skills
    op.create_index('ix_skills_professions', 'skills', ['professions'], unique=False)
    
    # Modification du type de la colonne rarity dans weapons
    op.alter_column('weapons', 'rarity',
           existing_type=sa.VARCHAR(length=20),
           type_=sa.Enum('JUNK', 'BASIC', 'FINE', 'MASTERWORK', 'RARE', 'EXOTIC', 'ASCENDED', 'LEGENDARY', name='rarity'),
           existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.alter_column('rarity',
               existing_type=sa.Enum('JUNK', 'BASIC', 'FINE', 'MASTERWORK', 'RARE', 'EXOTIC', 'ASCENDED', 'LEGENDARY', name='rarity'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('upgrade_components', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('trinkets', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_professions'))

    with op.batch_alter_table('profession_weapons', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_weapon_types', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_weapon_skills', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_trinkets', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_trinket_types', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_armors', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('profession_armor_types', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('item_stats', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('item_stat_mapping', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('infusions', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('armors', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
