"""Constantes et énumérations pour les mécaniques de jeu GW2."""

from enum import Enum, auto

class BuffType(Enum):
    """Types de buffs dans GW2."""
    MIGHT = "Might"
    FURY = "Fury"
    QUICKNESS = "Quickness"
    ALACRITY = "Alacrity"
    STABILITY = "Stability"
    PROTECTION = "Protection"
    REGENERATION = "Regeneration"
    VIGOR = "Vigor"
    SWIFTNESS = "Swiftness"
    AEGIS = "Aegis"
    RESISTANCE = "Resistance"
    RESOLUTION = "Resolution"
    VULNERABILITY = "Vulnerability"
    WEAKNESS = "Weakness"
    CHILLED = "Chilled"
    CRIPPLE = "Cripple"
    IMMOBILE = "Immobile"
    SLOW = "Slow"
    TAUNT = "Taunt"
    FEAR = "Fear"
    DIZZY = "Dizzy"
    STUN = "Stun"
    KNOCKDOWN = "Knockdown"
    PULL = "Pull"
    KNOCKBACK = "Knockback"
    LAUNCH = "Launch"
    FLOAT = "Float"
    SINK = "Sink"
    STUNBREAK = "Stunbreak"
    DODGE = "Dodge"
    EVADE = "Evade"
    INVULNERABILITY = "Invulnerability"
    REVEALED = "Revealed"
    STEALTH = "Stealth"
    SUPERSPEED = "Superspeed"
    BARRIER = "Barrier"

class ConditionType(Enum):
    """Types d'états altérés (conditions) dans GW2."""
    BLEEDING = "Bleeding"
    BURNING = "Burning"
    CONFUSION = "Confusion"
    POISON = "Poison"
    TORMENT = "Torment"
    BLIND = "Blind"
    CHILLED = "Chilled"
    CRIPPLED = "Crippled"
    FEAR = "Fear"
    IMMOBILE = "Immobile"
    SLOW = "Slow"
    TAUNT = "Taunt"
    WEAKNESS = "Weakness"
    VULNERABILITY = "Vulnerability"
    STUN = "Stun"
    DIZZY = "Dizzy"
    KNOCKDOWN = "Knockdown"

class BoonType(Enum):
    """Types de bonus (boons) dans GW2."""
    AEGIS = "Aegis"
    ALACRITY = "Alacrity"
    FURY = "Fury"
    MIGHT = "Might"
    PROTECTION = "Protection"
    QUICKNESS = "Quickness"
    REGENERATION = "Regeneration"
    RESISTANCE = "Resistance"
    RESOLUTION = "Resolution"
    STABILITY = "Stability"
    SWIFTNESS = "Swiftness"
    VIGOR = "Vigor"

class RoleType(Enum):
    """Types de rôles dans les groupes GW2."""
    HEALER = "Healer"
    SUPPORT = "Support"
    DPS = "DPS"
    CONDITION = "Condition"
    POWER = "Power"
    TANK = "Tank"
    BOON_SUPPORT = "Boon Support"
    BOON_DPS = "Boon DPS"
    HYBRID = "Hybrid"

class GameMode(Enum):
    """Modes de jeu dans GW2."""
    PVE = "PvE"
    PVP = "PvP"
    WVS = "WvW"
    WVW = "WvW"  # Alias
    PVE_OPEN_WORLD = "PvE Open World"
    PVE_FRACTALS = "Fractals"
    PVE_RAIDS = "Raids"
    PVE_STRIKES = "Strikes"
    PVE_DRMS = "DRMs"

class AttributeType(Enum):
    """Types d'attributs de personnage dans GW2."""
    POWER = "Power"
    PRECISION = "Precision"
    TOUGHNESS = "Toughness"
    VITALITY = "Vitality"
    CONCENTRATION = "Concentration"
    CONDITION_DAMAGE = "Condition Damage"
    EXPERTISE = "Expertise"
    FEROCITY = "Ferocity"
    HEALING_POWER = "Healing Power"
    BOON_DURATION = "Boon Duration"  # Concentration convertie
    CONDITION_DURATION = "Condition Duration"  # Expertise converti
    CRITICAL_CHANCE = "Critical Chance"  # Dérivé de Precision
    CRITICAL_DAMAGE = "Critical Damage"  # Dérivé de Ferocity

class DamageType(Enum):
    """Types de dégâts dans GW2."""
    STRIKE = "Strike"  # Dégâts directs
    CONDITION = "Condition"  # Dégâts de conditions
    PHYSICAL = "Physical"  # Dégâts physiques
    FIRE = "Fire"
    ICE = "Ice"
    LIGHTNING = "Lightning"
    CHAOS = "Chaos"
    DARK = "Dark"
    LIGHT = "Light"
    ENVIRONMENTAL = "Environmental"
    FALL = "Fall"
    DROWNING = "Drowning"

class ComboFieldType(Enum):
    """Types de champs de combo dans GW2."""
    FIRE = "Fire"
    ICE = "Ice"
    LIGHTNING = "Lightning"
    POISON = "Poison"
    LIGHT = "Light"
    DARK = "Dark"
    ETHEREAL = "Ethereal"
    SMOKE = "Smoke"
    WATER = "Water"

class ComboFinisherType(Enum):
    """Types de finisseurs de combo dans GW2."""
    BLAST = "Blast"
    LEAP = "Leap"
    PROJECTILE = "Projectile"
    WHIRL = "Whirl"

class SkillCategory(Enum):
    """Catégories de compétences dans GW2."""
    HEAL = "Heal"
    UTILITY = "Utility"
    ELITE = "Elite"
    WEAPON = "Weapon"
    PROFESSION = "Profession"
    DOWNED = "Downed"
    DODGE = "Dodge"
    PET = "Pet"
    BUNDLE = "Bundle"
    TOOLBELT = "Toolbelt"
    TRAIT = "Trait"
    TRANSFORMATION = "Transformation"
